language: csharp
mono: none
dist: trusty
dotnet: 2.2.401
solution: AldoGiovanniGiacomo.API.sln
install:
- dotnet restore
script:
- dotnet build
- dotnet test AldoGiovanniGiacomo.API.Test/AldoGiovanniGiacomo.API.Test.csproj
deploy:
  provider: azure_web_apps
  skip_cleanup: true
